### ISSUE TITLE
Unable to start container

### ISSUE THREAD

**Issue by moostmartijn** [anatosun/plexamp-docker#3]
Hi,

I'm running into some problems when I try to start this docker container on my Synology NAS DS923+

The following is in the logs:
```
2023/12/05 14:25:09 | stderr | This browser doesn't support cancelAnimationFrame. Make sure that you load a polyfill in older browsers. https://reactjs.org/link/react-polyfills
2023/12/05 14:25:09 | stderr | This browser doesn't support requestAnimationFrame. Make sure that you load a polyfill in older browsers. https://reactjs.org/link/react-polyfills
2023/12/05 14:24:42 | stdout | Error exchanging claim token.
2023/12/05 14:24:42 | stdout | Starting Plexamp 4.8.1

```

This is my config:

```
version: '3'
services:
  plexamp:
    container_name: plexamp
    privileged: true
    image: ghcr.io/anatosun/plexamp:amd64
    devices:
      - "/dev/snd:/dev/snd"
    volumes:
      - ./config:/root/.local/share/Plexamp/Settings # replace that with the appropriate host binding
    environment:
      - PLEXAMP_CLAIM_TOKEN=claim-mytoken # get your claim at https://www.plex.tv/claim/
      - PLEXAMP_PLAYER_NAME=docker # replace this with your player name
    ports:
      - 32500:32500
      - 20000:20000
    restart: unless-stopped
```
I hope this can be fixed.

Thanks in advance.
