### ISSUE TITLE
update to 4.9.10 broke my install

### ISSUE THREAD

**Issue by petikist** [anatosun/plexamp-docker#7]
Hello, 

everything was working flawlessly with my docker installation until tonight. I guess watchtower update to 4.9.10 and something is now broken. 
I'm on a RPI3b+, HomebridgeOS+docker and portainer.

My stack is : 
```
version: "3"
services:
  plexamp:
    container_name: plexamp
    network_mode: host
    privileged: true
    image: ghcr.io/anatosun/plexamp:arm32v7
    devices:
      - "/dev/snd:/dev/snd"
    volumes:
       - ./config:/root/.local/share/Plexamp/Settings # replace that with the appropriate host binding
    environment:
      - PLEXAMP_CLAIM_TOKEN=claim-_Axxxxxxxxxxxxxxx # get your claim at https://www.plex.tv/claim/
      - PLEXAMP_PLAYER_NAME=plex # replace this with your player name
    ports:
      - 32500:32500
      - 20000:20000
    restart: unless-stopped
```

and logs are : 
```
node:internal/modules/cjs/loader:1282
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^
Error: Module did not self-register: '/home/root/plexamp/treble/linux-arm/treble.node'.
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1282:18)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.81564 (/home/root/plexamp/js/index.js:2:352657)
    at r (/home/root/plexamp/js/index.js:2:3284581)
    at Object.2120 (/home/root/plexamp/js/index.js:2:347274)
    at r (/home/root/plexamp/js/index.js:2:3284581)
    at Object.81546 (/home/root/plexamp/js/index.js:2:334455) {
  code: 'ERR_DLOPEN_FAILED'
}

```

I'm on node v20.11.1

Any idea what could go wrong? 
Is it possible to tag the image to pull version 4.9.5 ? 

Thanks!
